### ISSUE TITLE
[MODIFY] DB 구조 수정

### ISSUE THREAD

**Issue by yoon1013** [Team-InIT/inIT_SERVER#13]
## 🌹 Issue
뷰 변경 및 관계 정의에 의한 db 변경사항입니다

## ☁ To-do
- [x] Recruit(지원) 테이블에 지원 포지션 추가
- [x] Zzim(찜한 공고) 관계 정의 수정
- [x] Todo(투두) 관계 정의 수정
