### ISSUE TITLE
[FEAT] 프로젝트 관련 api

### ISSUE THREAD

**Issue by yoon1013** [Team-InIT/inIT_SERVER#15]
## 🌹 Issue
프로젝트 관련 api입니다

## ☁ To-do
- [x] 모집중 프로젝트 전체보기
- [x] 모집완료 프로젝트 전체보기
- [x] 프로젝트 상세보기 api 수정
