### ISSUE TITLE
[MODIFY] DB 수정

### ISSUE THREAD

**Issue by yoon1013** [Team-InIT/inIT_SERVER#7]
## 🌹 Issue
기획 변경으로 인한 DB 변경관련 작업입니다.

## ☁ To-do
- [x] mysql db 연결
- [x] 테이블 모델 만들기
- [x] db 연결 테스트
