### ISSUE TITLE
[FEAT] 홈 화면 관련 api

### ISSUE THREAD

**Issue by yoon1013** [Team-InIT/inIT_SERVER#8]
## 🌹 Issue
홈 화면과 관련된 api 개발

## ☁ To-do
- [x] 소속 프로젝트 전체보기
- [x] 추천 프로젝트 전체보기
- [x] 소속 프로젝트(3개), 추천 프로젝트(3개)
